name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '34 6 * * 3'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set Image Tag
        id: image_tag
        run: |
          echo ::set-output name=tag_value::us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:${{ github.sha }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t "${{ steps.image_tag.outputs.tag_value }}" .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.image_tag.outputs.tag_value }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
